[package]
name = "amethyst_precompile"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[dependencies.amethyst]
version = "0.15.3"
features = ["vulkan"]
default-features = false
